//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.18 at 02:29:52 PM CET 
//


package eu.fp7.secured.mspl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RemoveAdvertisementAction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RemoveAdvertisementAction">
 *   &lt;complexContent>
 *     &lt;extension base="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}RemoveAction">
 *       &lt;sequence>
 *         &lt;element name="RemoveAdvertisementActionType" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}RemoveAdvertisementActionType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RemoveAdvertisementAction", propOrder = {
    "removeAdvertisementActionType"
})
public class RemoveAdvertisementAction
    extends RemoveAction
{

    @XmlElement(name = "RemoveAdvertisementActionType", required = true)
    protected RemoveAdvertisementActionType removeAdvertisementActionType;

    /**
     * Gets the value of the removeAdvertisementActionType property.
     * 
     * @return
     *     possible object is
     *     {@link RemoveAdvertisementActionType }
     *     
     */
    public RemoveAdvertisementActionType getRemoveAdvertisementActionType() {
        return removeAdvertisementActionType;
    }

    /**
     * Sets the value of the removeAdvertisementActionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RemoveAdvertisementActionType }
     *     
     */
    public void setRemoveAdvertisementActionType(RemoveAdvertisementActionType value) {
        this.removeAdvertisementActionType = value;
    }

}
