//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.18 at 02:29:52 PM CET 
//


package eu.fp7.secured.mspl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Site2SiteNetworkConfiguration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Site2SiteNetworkConfiguration">
 *   &lt;complexContent>
 *     &lt;extension base="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}AdditionalNetworkConfigurationParameters">
 *       &lt;sequence>
 *         &lt;element name="localNetwork" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="remoteNetwork" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="localNetworkNetmask" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="remoteNetworkNetmask" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Site2SiteNetworkConfiguration", propOrder = {
    "localNetwork",
    "remoteNetwork",
    "localNetworkNetmask",
    "remoteNetworkNetmask"
})
public class Site2SiteNetworkConfiguration
    extends AdditionalNetworkConfigurationParameters
{

    protected String localNetwork;
    protected String remoteNetwork;
    protected String localNetworkNetmask;
    protected String remoteNetworkNetmask;

    /**
     * Gets the value of the localNetwork property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalNetwork() {
        return localNetwork;
    }

    /**
     * Sets the value of the localNetwork property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalNetwork(String value) {
        this.localNetwork = value;
    }

    /**
     * Gets the value of the remoteNetwork property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemoteNetwork() {
        return remoteNetwork;
    }

    /**
     * Sets the value of the remoteNetwork property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemoteNetwork(String value) {
        this.remoteNetwork = value;
    }

    /**
     * Gets the value of the localNetworkNetmask property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalNetworkNetmask() {
        return localNetworkNetmask;
    }

    /**
     * Sets the value of the localNetworkNetmask property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalNetworkNetmask(String value) {
        this.localNetworkNetmask = value;
    }

    /**
     * Gets the value of the remoteNetworkNetmask property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemoteNetworkNetmask() {
        return remoteNetworkNetmask;
    }

    /**
     * Sets the value of the remoteNetworkNetmask property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemoteNetworkNetmask(String value) {
        this.remoteNetworkNetmask = value;
    }

}
