/**********************************************************************************************
 * Copyright (c) 2016 Politecnico di Torino.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Contributors:
 *   - POLITO TorSec Team: Fulvio Valenza, Christian Pitscheider, Cataldo Basile, Marco Vallini 
 *	 - SECURED Team 
 *	 - Corresponding: fulvio.valenza@polito.it, cataldo.basile@polito.it
 ************************************************************************************************/
//created on: 16-mar-2015
package rules

//list any import classes here.
import main.java.hspl_class.*;


//declare any global variables here




rule "Non-enforzability"
    when
    c : Capability()
    e : SuitablePSA(e.getCapability().equals(c) && 	e.getPsaList().getPsa().isEmpty())
    h : Hspl(h.getCapabilities().getCapabilityList().contains(c) && h.getCandidates().getSuitablePSAList().contains(e) )   
          
    then
    	h.setEnforzability(false);
    	h.getNonEnforzableCapability().getCapabilityList().add(c);
    
end


rule "Non-enforzability_MSPL"
    when
    c : Capability()
    e : SuitablePSA(e.getCapability().equals(c) && 	e.getPsaList().getPsa().isEmpty())
    m : MSPL(m.getCapabilities().getCapabilityList().contains(c) && m.getCandidates().getSuitablePSAList().contains(e) )   
          
    then
    	m.setEnforzability(false);
    	m.getNonEnforzableCapability().getCapabilityList().add(c);
end

