//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.19 at 01:06:33 PM CEST 
//


package main.java.mspl_class;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HSPL complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HSPL">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="HSPL_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="HSPL_text" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HSPL")
public class HSPL {

    @XmlAttribute(name = "HSPL_id")
    protected String hsplId;
    @XmlAttribute(name = "HSPL_text")
    protected String hsplText;

    /**
     * Gets the value of the hsplId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHSPLId() {
        return hsplId;
    }

    /**
     * Sets the value of the hsplId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHSPLId(String value) {
        this.hsplId = value;
    }

    /**
     * Gets the value of the hsplText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHSPLText() {
        return hsplText;
    }

    /**
     * Sets the value of the hsplText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHSPLText(String value) {
        this.hsplText = value;
    }

}
