//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.19 at 01:06:33 PM CEST 
//


package main.java.mspl_class;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LoggingCondition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoggingCondition">
 *   &lt;complexContent>
 *     &lt;extension base="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}ConfigurationCondition">
 *       &lt;sequence>
 *         &lt;element name="eventCondition" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}EventCondition" minOccurs="0"/>
 *         &lt;element name="object" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="packetCondition" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}PacketFilterCondition" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="applicationCondition" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}ApplicationLayerCondition" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoggingCondition", propOrder = {
    "eventCondition",
    "object",
    "packetCondition",
    "applicationCondition"
})
public class LoggingCondition
    extends ConfigurationCondition
{

    protected EventCondition eventCondition;
    protected String object;
    protected List<PacketFilterCondition> packetCondition;
    protected List<ApplicationLayerCondition> applicationCondition;

    /**
     * Gets the value of the eventCondition property.
     * 
     * @return
     *     possible object is
     *     {@link EventCondition }
     *     
     */
    public EventCondition getEventCondition() {
        return eventCondition;
    }

    /**
     * Sets the value of the eventCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventCondition }
     *     
     */
    public void setEventCondition(EventCondition value) {
        this.eventCondition = value;
    }

    /**
     * Gets the value of the object property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObject() {
        return object;
    }

    /**
     * Sets the value of the object property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObject(String value) {
        this.object = value;
    }

    /**
     * Gets the value of the packetCondition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the packetCondition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPacketCondition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PacketFilterCondition }
     * 
     * 
     */
    public List<PacketFilterCondition> getPacketCondition() {
        if (packetCondition == null) {
            packetCondition = new ArrayList<PacketFilterCondition>();
        }
        return this.packetCondition;
    }

    /**
     * Gets the value of the applicationCondition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the applicationCondition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApplicationCondition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ApplicationLayerCondition }
     * 
     * 
     */
    public List<ApplicationLayerCondition> getApplicationCondition() {
        if (applicationCondition == null) {
            applicationCondition = new ArrayList<ApplicationLayerCondition>();
        }
        return this.applicationCondition;
    }

}
