//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.19 at 01:06:33 PM CEST 
//


package main.java.mspl_class;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for XMLDataSelectionCondition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XMLDataSelectionCondition">
 *   &lt;complexContent>
 *     &lt;extension base="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}DataSelectionCondition">
 *       &lt;sequence>
 *         &lt;element name="xmlDataType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="xmlNameSpace" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="xmlQueryLanguage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="xmlQueryLanguageVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="xmlQueryExpression" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XMLDataSelectionCondition", propOrder = {
    "xmlDataType",
    "xmlNameSpace",
    "xmlQueryLanguage",
    "xmlQueryLanguageVersion",
    "xmlQueryExpression"
})
@XmlSeeAlso({
    WSSecurityCondition.class
})
public class XMLDataSelectionCondition
    extends DataSelectionCondition
{

    @XmlElement(required = true)
    protected String xmlDataType;
    @XmlElement(required = true)
    protected String xmlNameSpace;
    @XmlElement(required = true)
    protected String xmlQueryLanguage;
    @XmlElement(required = true)
    protected String xmlQueryLanguageVersion;
    @XmlElement(required = true)
    protected String xmlQueryExpression;

    /**
     * Gets the value of the xmlDataType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlDataType() {
        return xmlDataType;
    }

    /**
     * Sets the value of the xmlDataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlDataType(String value) {
        this.xmlDataType = value;
    }

    /**
     * Gets the value of the xmlNameSpace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlNameSpace() {
        return xmlNameSpace;
    }

    /**
     * Sets the value of the xmlNameSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlNameSpace(String value) {
        this.xmlNameSpace = value;
    }

    /**
     * Gets the value of the xmlQueryLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlQueryLanguage() {
        return xmlQueryLanguage;
    }

    /**
     * Sets the value of the xmlQueryLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlQueryLanguage(String value) {
        this.xmlQueryLanguage = value;
    }

    /**
     * Gets the value of the xmlQueryLanguageVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlQueryLanguageVersion() {
        return xmlQueryLanguageVersion;
    }

    /**
     * Sets the value of the xmlQueryLanguageVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlQueryLanguageVersion(String value) {
        this.xmlQueryLanguageVersion = value;
    }

    /**
     * Gets the value of the xmlQueryExpression property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlQueryExpression() {
        return xmlQueryExpression;
    }

    /**
     * Sets the value of the xmlQueryExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlQueryExpression(String value) {
        this.xmlQueryExpression = value;
    }

}
