//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.05.14 at 09:55:21 AM CEST
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/SchemaFile_Schema")
package main.java.schemaFile_class;
