//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.25 at 11:07:59 AM CET 
//


package eu.fp7.secured.mspl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FilteringCapability complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FilteringCapability">
 *   &lt;complexContent>
 *     &lt;extension base="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}ChannelAuthorizationCapability">
 *       &lt;sequence>
 *         &lt;element name="stateful" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="applicationLayerFiltering" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="httpFiltering" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="contentInspection" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FilteringCapability", propOrder = {
    "stateful",
    "applicationLayerFiltering",
    "httpFiltering",
    "contentInspection"
})
public class FilteringCapability
    extends ChannelAuthorizationCapability
{

    protected boolean stateful;
    protected boolean applicationLayerFiltering;
    protected boolean httpFiltering;
    protected boolean contentInspection;

    /**
     * Gets the value of the stateful property.
     * 
     */
    public boolean isStateful() {
        return stateful;
    }

    /**
     * Sets the value of the stateful property.
     * 
     */
    public void setStateful(boolean value) {
        this.stateful = value;
    }

    /**
     * Gets the value of the applicationLayerFiltering property.
     * 
     */
    public boolean isApplicationLayerFiltering() {
        return applicationLayerFiltering;
    }

    /**
     * Sets the value of the applicationLayerFiltering property.
     * 
     */
    public void setApplicationLayerFiltering(boolean value) {
        this.applicationLayerFiltering = value;
    }

    /**
     * Gets the value of the httpFiltering property.
     * 
     */
    public boolean isHttpFiltering() {
        return httpFiltering;
    }

    /**
     * Sets the value of the httpFiltering property.
     * 
     */
    public void setHttpFiltering(boolean value) {
        this.httpFiltering = value;
    }

    /**
     * Gets the value of the contentInspection property.
     * 
     */
    public boolean isContentInspection() {
        return contentInspection;
    }

    /**
     * Sets the value of the contentInspection property.
     * 
     */
    public void setContentInspection(boolean value) {
        this.contentInspection = value;
    }

}
