//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.11.25 at 11:07:59 AM CET
//


package eu.fp7.secured.mspl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RuleSetConfiguration complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="RuleSetConfiguration">
 *   &lt;complexContent>
 *     &lt;extension base="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}Configuration">
 *       &lt;sequence>
 *         &lt;element name="defaultAction" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}ConfigurationAction" minOccurs="0"/>
 *         &lt;element name="configurationRule" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}ConfigurationRule" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="resolutionStrategy" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}ResolutionStrategy"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RuleSetConfiguration", propOrder = {
    "defaultAction",
    "configurationRule",
    "resolutionStrategy",
    "name"
})
public class RuleSetConfiguration
    extends Configuration
{

    protected ConfigurationAction defaultAction;
    protected List<ConfigurationRule> configurationRule;
    @XmlElement(required = true)
    protected ResolutionStrategy resolutionStrategy;
    @XmlElement(name = "Name", required = true)
    protected String name;

    /**
     * Gets the value of the defaultAction property.
     *
     * @return
     *     possible object is
     *     {@link ConfigurationAction }
     *
     */
    public ConfigurationAction getDefaultAction() {
        return defaultAction;
    }

    /**
     * Sets the value of the defaultAction property.
     *
     * @param value
     *     allowed object is
     *     {@link ConfigurationAction }
     *
     */
    public void setDefaultAction(ConfigurationAction value) {
        this.defaultAction = value;
    }

    /**
     * Gets the value of the configurationRule property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the configurationRule property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConfigurationRule().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConfigurationRule }
     *
     *
     */
    public List<ConfigurationRule> getConfigurationRule() {
        if (configurationRule == null) {
            configurationRule = new ArrayList<ConfigurationRule>();
        }
        return this.configurationRule;
    }

    /**
     * Gets the value of the resolutionStrategy property.
     *
     * @return
     *     possible object is
     *     {@link ResolutionStrategy }
     *
     */
    public ResolutionStrategy getResolutionStrategy() {
        return resolutionStrategy;
    }

    /**
     * Sets the value of the resolutionStrategy property.
     *
     * @param value
     *     allowed object is
     *     {@link ResolutionStrategy }
     *
     */
    public void setResolutionStrategy(ResolutionStrategy value) {
        this.resolutionStrategy = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

}
