//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.18 at 02:29:52 PM CET 
//


package eu.fp7.secured.mspl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AuthenticationParameters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AuthenticationParameters">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="psKey_value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="psKey_path" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ca_path" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cert_path" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="publicKey_path" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="publicKey_filename" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="publicKey_passphrase" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ca_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ca_filename" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cert_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cert_filename" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="remote_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AuthenticationParameters", propOrder = {
    "psKeyValue",
    "psKeyPath",
    "caPath",
    "certPath",
    "publicKeyPath",
    "publicKeyFilename",
    "publicKeyPassphrase",
    "caId",
    "caFilename",
    "certId",
    "certFilename",
    "remoteId"
})
public class AuthenticationParameters {

    @XmlElement(name = "psKey_value")
    protected String psKeyValue;
    @XmlElement(name = "psKey_path")
    protected String psKeyPath;
    @XmlElement(name = "ca_path")
    protected String caPath;
    @XmlElement(name = "cert_path")
    protected String certPath;
    @XmlElement(name = "publicKey_path")
    protected String publicKeyPath;
    @XmlElement(name = "publicKey_filename")
    protected String publicKeyFilename;
    @XmlElement(name = "publicKey_passphrase")
    protected String publicKeyPassphrase;
    @XmlElement(name = "ca_id")
    protected String caId;
    @XmlElement(name = "ca_filename")
    protected String caFilename;
    @XmlElement(name = "cert_id")
    protected String certId;
    @XmlElement(name = "cert_filename")
    protected String certFilename;
    @XmlElement(name = "remote_id")
    protected String remoteId;

    /**
     * Gets the value of the psKeyValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPsKeyValue() {
        return psKeyValue;
    }

    /**
     * Sets the value of the psKeyValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPsKeyValue(String value) {
        this.psKeyValue = value;
    }

    /**
     * Gets the value of the psKeyPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPsKeyPath() {
        return psKeyPath;
    }

    /**
     * Sets the value of the psKeyPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPsKeyPath(String value) {
        this.psKeyPath = value;
    }

    /**
     * Gets the value of the caPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaPath() {
        return caPath;
    }

    /**
     * Sets the value of the caPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaPath(String value) {
        this.caPath = value;
    }

    /**
     * Gets the value of the certPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertPath() {
        return certPath;
    }

    /**
     * Sets the value of the certPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertPath(String value) {
        this.certPath = value;
    }

    /**
     * Gets the value of the publicKeyPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicKeyPath() {
        return publicKeyPath;
    }

    /**
     * Sets the value of the publicKeyPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicKeyPath(String value) {
        this.publicKeyPath = value;
    }

    /**
     * Gets the value of the publicKeyFilename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicKeyFilename() {
        return publicKeyFilename;
    }

    /**
     * Sets the value of the publicKeyFilename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicKeyFilename(String value) {
        this.publicKeyFilename = value;
    }

    /**
     * Gets the value of the publicKeyPassphrase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicKeyPassphrase() {
        return publicKeyPassphrase;
    }

    /**
     * Sets the value of the publicKeyPassphrase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicKeyPassphrase(String value) {
        this.publicKeyPassphrase = value;
    }

    /**
     * Gets the value of the caId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaId() {
        return caId;
    }

    /**
     * Sets the value of the caId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaId(String value) {
        this.caId = value;
    }

    /**
     * Gets the value of the caFilename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaFilename() {
        return caFilename;
    }

    /**
     * Sets the value of the caFilename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaFilename(String value) {
        this.caFilename = value;
    }

    /**
     * Gets the value of the certId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertId() {
        return certId;
    }

    /**
     * Sets the value of the certId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertId(String value) {
        this.certId = value;
    }

    /**
     * Gets the value of the certFilename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertFilename() {
        return certFilename;
    }

    /**
     * Sets the value of the certFilename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertFilename(String value) {
        this.certFilename = value;
    }

    /**
     * Gets the value of the remoteId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemoteId() {
        return remoteId;
    }

    /**
     * Sets the value of the remoteId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemoteId(String value) {
        this.remoteId = value;
    }

}
