//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.18 at 02:29:52 PM CET 
//


package eu.fp7.secured.mspl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IKETechnologyParameter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IKETechnologyParameter">
 *   &lt;complexContent>
 *     &lt;extension base="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}TechnologySpecificParameters">
 *       &lt;sequence>
 *         &lt;element name="phase2_pfs_group" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="exchangeMode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="phase1_dh_group" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="phase2_compression_algorithm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="hash_algorithm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ESN" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="encryptionAlgorithm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lifetime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rekey_margin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="keyring_tries" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MOBIKE" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IKETechnologyParameter", propOrder = {
    "phase2PfsGroup",
    "exchangeMode",
    "phase1DhGroup",
    "phase2CompressionAlgorithm",
    "hashAlgorithm",
    "esn",
    "encryptionAlgorithm",
    "lifetime",
    "rekeyMargin",
    "keyringTries",
    "mobike"
})
public class IKETechnologyParameter
    extends TechnologySpecificParameters
{

    @XmlElement(name = "phase2_pfs_group")
    protected String phase2PfsGroup;
    protected String exchangeMode;
    @XmlElement(name = "phase1_dh_group")
    protected String phase1DhGroup;
    @XmlElement(name = "phase2_compression_algorithm")
    protected String phase2CompressionAlgorithm;
    @XmlElement(name = "hash_algorithm")
    protected String hashAlgorithm;
    @XmlElement(name = "ESN")
    protected Boolean esn;
    @XmlElement(required = true)
    protected String encryptionAlgorithm;
    protected String lifetime;
    @XmlElement(name = "rekey_margin")
    protected String rekeyMargin;
    @XmlElement(name = "keyring_tries")
    protected String keyringTries;
    @XmlElement(name = "MOBIKE")
    protected Boolean mobike;

    /**
     * Gets the value of the phase2PfsGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhase2PfsGroup() {
        return phase2PfsGroup;
    }

    /**
     * Sets the value of the phase2PfsGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhase2PfsGroup(String value) {
        this.phase2PfsGroup = value;
    }

    /**
     * Gets the value of the exchangeMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExchangeMode() {
        return exchangeMode;
    }

    /**
     * Sets the value of the exchangeMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExchangeMode(String value) {
        this.exchangeMode = value;
    }

    /**
     * Gets the value of the phase1DhGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhase1DhGroup() {
        return phase1DhGroup;
    }

    /**
     * Sets the value of the phase1DhGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhase1DhGroup(String value) {
        this.phase1DhGroup = value;
    }

    /**
     * Gets the value of the phase2CompressionAlgorithm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhase2CompressionAlgorithm() {
        return phase2CompressionAlgorithm;
    }

    /**
     * Sets the value of the phase2CompressionAlgorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhase2CompressionAlgorithm(String value) {
        this.phase2CompressionAlgorithm = value;
    }

    /**
     * Gets the value of the hashAlgorithm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHashAlgorithm() {
        return hashAlgorithm;
    }

    /**
     * Sets the value of the hashAlgorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHashAlgorithm(String value) {
        this.hashAlgorithm = value;
    }

    /**
     * Gets the value of the esn property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isESN() {
        return esn;
    }

    /**
     * Sets the value of the esn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setESN(Boolean value) {
        this.esn = value;
    }

    /**
     * Gets the value of the encryptionAlgorithm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncryptionAlgorithm() {
        return encryptionAlgorithm;
    }

    /**
     * Sets the value of the encryptionAlgorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncryptionAlgorithm(String value) {
        this.encryptionAlgorithm = value;
    }

    /**
     * Gets the value of the lifetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLifetime() {
        return lifetime;
    }

    /**
     * Sets the value of the lifetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLifetime(String value) {
        this.lifetime = value;
    }

    /**
     * Gets the value of the rekeyMargin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRekeyMargin() {
        return rekeyMargin;
    }

    /**
     * Sets the value of the rekeyMargin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRekeyMargin(String value) {
        this.rekeyMargin = value;
    }

    /**
     * Gets the value of the keyringTries property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyringTries() {
        return keyringTries;
    }

    /**
     * Sets the value of the keyringTries property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyringTries(String value) {
        this.keyringTries = value;
    }

    /**
     * Gets the value of the mobike property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMOBIKE() {
        return mobike;
    }

    /**
     * Sets the value of the mobike property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMOBIKE(Boolean value) {
        this.mobike = value;
    }

}
