//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.05.17 at 03:01:47 PM CEST
//


package main.java.matching_class;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Hspl_ID complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Hspl_ID">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="hspl" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Hspl_ID")
public class HsplID {

    @XmlAttribute(name = "hspl")
    protected String hspl;

    /**
     * Gets the value of the hspl property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getHspl() {
        return hspl;
    }

    /**
     * Sets the value of the hspl property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHspl(String value) {
        this.hspl = value;
    }

}
