//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.05.17 at 03:01:47 PM CEST
//


package main.java.matching_class;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the matching_class package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: matching_class
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Matching }
     *
     */
    public Matching createMatching() {
        return new Matching();
    }

    /**
     * Create an instance of {@link Couple }
     *
     */
    public Couple createCouple() {
        return new Couple();
    }

    /**
     * Create an instance of {@link HsplID }
     *
     */
    public HsplID createHsplID() {
        return new HsplID();
    }

}
