//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.05.17 at 03:01:47 PM CEST
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/matching_Schema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package main.java.matching_class;
