//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.20 at 05:38:59 PM CEST 
//


package eu.fp7.secured.mspl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HTTPCondition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HTTPCondition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="httpMetod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="browser" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="user_cert" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ca_cert" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="request_mime_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="response_mime_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="http_regex_header" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="http_status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HTTPCondition", propOrder = {
    "httpMetod",
    "browser",
    "userCert",
    "caCert",
    "requestMimeType",
    "responseMimeType",
    "httpRegexHeader",
    "httpStatus"
})
public class HTTPCondition {

    protected String httpMetod;
    protected String browser;
    @XmlElement(name = "user_cert")
    protected String userCert;
    @XmlElement(name = "ca_cert")
    protected String caCert;
    @XmlElement(name = "request_mime_type")
    protected String requestMimeType;
    @XmlElement(name = "response_mime_type")
    protected String responseMimeType;
    @XmlElement(name = "http_regex_header")
    protected String httpRegexHeader;
    @XmlElement(name = "http_status")
    protected String httpStatus;

    /**
     * Gets the value of the httpMetod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHttpMetod() {
        return httpMetod;
    }

    /**
     * Sets the value of the httpMetod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHttpMetod(String value) {
        this.httpMetod = value;
    }

    /**
     * Gets the value of the browser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrowser() {
        return browser;
    }

    /**
     * Sets the value of the browser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrowser(String value) {
        this.browser = value;
    }

    /**
     * Gets the value of the userCert property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserCert() {
        return userCert;
    }

    /**
     * Sets the value of the userCert property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserCert(String value) {
        this.userCert = value;
    }

    /**
     * Gets the value of the caCert property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaCert() {
        return caCert;
    }

    /**
     * Sets the value of the caCert property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaCert(String value) {
        this.caCert = value;
    }

    /**
     * Gets the value of the requestMimeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestMimeType() {
        return requestMimeType;
    }

    /**
     * Sets the value of the requestMimeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestMimeType(String value) {
        this.requestMimeType = value;
    }

    /**
     * Gets the value of the responseMimeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseMimeType() {
        return responseMimeType;
    }

    /**
     * Sets the value of the responseMimeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseMimeType(String value) {
        this.responseMimeType = value;
    }

    /**
     * Gets the value of the httpRegexHeader property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHttpRegexHeader() {
        return httpRegexHeader;
    }

    /**
     * Sets the value of the httpRegexHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHttpRegexHeader(String value) {
        this.httpRegexHeader = value;
    }

    /**
     * Gets the value of the httpStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHttpStatus() {
        return httpStatus;
    }

    /**
     * Sets the value of the httpStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHttpStatus(String value) {
        this.httpStatus = value;
    }

}
