//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.20 at 05:38:59 PM CEST 
//


package eu.fp7.secured.mspl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Integrity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Integrity">
 *   &lt;complexContent>
 *     &lt;extension base="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}TechnologyActionSecurityProperty">
 *       &lt;sequence>
 *         &lt;element name="integrityAlgorithm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="integrityHeader" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="integrityPayload" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Integrity", propOrder = {
    "integrityAlgorithm",
    "integrityHeader",
    "integrityPayload"
})
public class Integrity
    extends TechnologyActionSecurityProperty
{

    protected String integrityAlgorithm;
    protected Boolean integrityHeader;
    protected Boolean integrityPayload;

    /**
     * Gets the value of the integrityAlgorithm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntegrityAlgorithm() {
        return integrityAlgorithm;
    }

    /**
     * Sets the value of the integrityAlgorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntegrityAlgorithm(String value) {
        this.integrityAlgorithm = value;
    }

    /**
     * Gets the value of the integrityHeader property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIntegrityHeader() {
        return integrityHeader;
    }

    /**
     * Sets the value of the integrityHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIntegrityHeader(Boolean value) {
        this.integrityHeader = value;
    }

    /**
     * Gets the value of the integrityPayload property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIntegrityPayload() {
        return integrityPayload;
    }

    /**
     * Sets the value of the integrityPayload property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIntegrityPayload(Boolean value) {
        this.integrityPayload = value;
    }

}
