//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.20 at 05:38:59 PM CEST 
//


package eu.fp7.secured.mspl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ParentalControlAction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ParentalControlAction">
 *   &lt;complexContent>
 *     &lt;extension base="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}EnableAction">
 *       &lt;sequence>
 *         &lt;element name="pics" type="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}Pics" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParentalControlAction", propOrder = {
    "pics"
})
public class ParentalControlAction
    extends EnableAction
{

    protected Pics pics;

    /**
     * Gets the value of the pics property.
     * 
     * @return
     *     possible object is
     *     {@link Pics }
     *     
     */
    public Pics getPics() {
        return pics;
    }

    /**
     * Sets the value of the pics property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pics }
     *     
     */
    public void setPics(Pics value) {
        this.pics = value;
    }

}
