//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.25 at 11:07:59 AM CET 
//


package eu.fp7.secured.mspl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IKETechnologyParameter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IKETechnologyParameter">
 *   &lt;complexContent>
 *     &lt;extension base="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}TechnologySpecificParameters">
 *       &lt;sequence>
 *         &lt;element name="phase2_pfs_group" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="exchangeMode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phase1_dh_group" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phase2_compression_algorithm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hash_algorithm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IKETechnologyParameter", propOrder = {
    "phase2PfsGroup",
    "exchangeMode",
    "phase1DhGroup",
    "phase2CompressionAlgorithm",
    "hashAlgorithm"
})
public class IKETechnologyParameter
    extends TechnologySpecificParameters
{

    @XmlElement(name = "phase2_pfs_group", required = true)
    protected String phase2PfsGroup;
    @XmlElement(required = true)
    protected String exchangeMode;
    @XmlElement(name = "phase1_dh_group", required = true)
    protected String phase1DhGroup;
    @XmlElement(name = "phase2_compression_algorithm", required = true)
    protected String phase2CompressionAlgorithm;
    @XmlElement(name = "hash_algorithm", required = true)
    protected String hashAlgorithm;

    /**
     * Gets the value of the phase2PfsGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhase2PfsGroup() {
        return phase2PfsGroup;
    }

    /**
     * Sets the value of the phase2PfsGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhase2PfsGroup(String value) {
        this.phase2PfsGroup = value;
    }

    /**
     * Gets the value of the exchangeMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExchangeMode() {
        return exchangeMode;
    }

    /**
     * Sets the value of the exchangeMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExchangeMode(String value) {
        this.exchangeMode = value;
    }

    /**
     * Gets the value of the phase1DhGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhase1DhGroup() {
        return phase1DhGroup;
    }

    /**
     * Sets the value of the phase1DhGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhase1DhGroup(String value) {
        this.phase1DhGroup = value;
    }

    /**
     * Gets the value of the phase2CompressionAlgorithm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhase2CompressionAlgorithm() {
        return phase2CompressionAlgorithm;
    }

    /**
     * Sets the value of the phase2CompressionAlgorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhase2CompressionAlgorithm(String value) {
        this.phase2CompressionAlgorithm = value;
    }

    /**
     * Gets the value of the hashAlgorithm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHashAlgorithm() {
        return hashAlgorithm;
    }

    /**
     * Sets the value of the hashAlgorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHashAlgorithm(String value) {
        this.hashAlgorithm = value;
    }

}
