//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.25 at 11:07:59 AM CET 
//


package eu.fp7.secured.mspl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WSSecurityCondition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WSSecurityCondition">
 *   &lt;complexContent>
 *     &lt;extension base="{http://modeliosoft/xsddesigner/a22bd60b-ee3d-425c-8618-beb6a854051a/ITResource.xsd}XMLDataSelectionCondition">
 *       &lt;sequence>
 *         &lt;element name="content_vs_element" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="body" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="attachment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="headerLocalName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="headerNameSpace" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WSSecurityCondition", propOrder = {
    "contentVsElement",
    "body",
    "attachment",
    "headerLocalName",
    "headerNameSpace"
})
public class WSSecurityCondition
    extends XMLDataSelectionCondition
{

    @XmlElement(name = "content_vs_element")
    protected boolean contentVsElement;
    @XmlElement(required = true)
    protected String body;
    @XmlElement(required = true)
    protected String attachment;
    @XmlElement(required = true)
    protected String headerLocalName;
    @XmlElement(required = true)
    protected String headerNameSpace;

    /**
     * Gets the value of the contentVsElement property.
     * 
     */
    public boolean isContentVsElement() {
        return contentVsElement;
    }

    /**
     * Sets the value of the contentVsElement property.
     * 
     */
    public void setContentVsElement(boolean value) {
        this.contentVsElement = value;
    }

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBody(String value) {
        this.body = value;
    }

    /**
     * Gets the value of the attachment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttachment() {
        return attachment;
    }

    /**
     * Sets the value of the attachment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttachment(String value) {
        this.attachment = value;
    }

    /**
     * Gets the value of the headerLocalName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeaderLocalName() {
        return headerLocalName;
    }

    /**
     * Sets the value of the headerLocalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeaderLocalName(String value) {
        this.headerLocalName = value;
    }

    /**
     * Gets the value of the headerNameSpace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeaderNameSpace() {
        return headerNameSpace;
    }

    /**
     * Sets the value of the headerNameSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeaderNameSpace(String value) {
        this.headerNameSpace = value;
    }

}
