//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.29 at 10:28:31 AM CET 
//


package main.java.hspl_class;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fields complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fields">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="time_period" type="{http://www.example.org/Refinement_Schema}time_period" minOccurs="0"/>
 *         &lt;element name="traffic_target" type="{http://www.example.org/Refinement_Schema}traffic_target" minOccurs="0"/>
 *         &lt;element name="specific_URL" type="{http://www.example.org/Refinement_Schema}specific_URL" minOccurs="0"/>
 *         &lt;element name="type_content" type="{http://www.example.org/Refinement_Schema}type_Content" minOccurs="0"/>
 *         &lt;element name="purpose" type="{http://www.example.org/Refinement_Schema}purpose" minOccurs="0"/>
 *         &lt;element name="resource_values" type="{http://www.example.org/Refinement_Schema}resource_values" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="downlink_bandwidth_value" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="uplink_bandwidth_value" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="country" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fields", propOrder = {
    "timePeriod",
    "trafficTarget",
    "specificURL",
    "typeContent",
    "purpose",
    "resourceValues"
})
public class Fields {

    @XmlElement(name = "time_period")
    protected TimePeriod timePeriod;
    @XmlElement(name = "traffic_target")
    protected TrafficTarget trafficTarget;
    @XmlElement(name = "specific_URL")
    protected SpecificURL specificURL;
    @XmlElement(name = "type_content")
    protected TypeContent typeContent;
    protected Purpose purpose;
    @XmlElement(name = "resource_values")
    protected ResourceValues resourceValues;
    @XmlAttribute(name = "downlink_bandwidth_value")
    protected Double downlinkBandwidthValue;
    @XmlAttribute(name = "uplink_bandwidth_value")
    protected Double uplinkBandwidthValue;
    @XmlAttribute(name = "country")
    protected String country;

    /**
     * Gets the value of the timePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link TimePeriod }
     *     
     */
    public TimePeriod getTimePeriod() {
        return timePeriod;
    }

    /**
     * Sets the value of the timePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimePeriod }
     *     
     */
    public void setTimePeriod(TimePeriod value) {
        this.timePeriod = value;
    }

    /**
     * Gets the value of the trafficTarget property.
     * 
     * @return
     *     possible object is
     *     {@link TrafficTarget }
     *     
     */
    public TrafficTarget getTrafficTarget() {
        return trafficTarget;
    }

    /**
     * Sets the value of the trafficTarget property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrafficTarget }
     *     
     */
    public void setTrafficTarget(TrafficTarget value) {
        this.trafficTarget = value;
    }

    /**
     * Gets the value of the specificURL property.
     * 
     * @return
     *     possible object is
     *     {@link SpecificURL }
     *     
     */
    public SpecificURL getSpecificURL() {
        return specificURL;
    }

    /**
     * Sets the value of the specificURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecificURL }
     *     
     */
    public void setSpecificURL(SpecificURL value) {
        this.specificURL = value;
    }

    /**
     * Gets the value of the typeContent property.
     * 
     * @return
     *     possible object is
     *     {@link TypeContent }
     *     
     */
    public TypeContent getTypeContent() {
        return typeContent;
    }

    /**
     * Sets the value of the typeContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeContent }
     *     
     */
    public void setTypeContent(TypeContent value) {
        this.typeContent = value;
    }

    /**
     * Gets the value of the purpose property.
     * 
     * @return
     *     possible object is
     *     {@link Purpose }
     *     
     */
    public Purpose getPurpose() {
        return purpose;
    }

    /**
     * Sets the value of the purpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link Purpose }
     *     
     */
    public void setPurpose(Purpose value) {
        this.purpose = value;
    }

    /**
     * Gets the value of the resourceValues property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceValues }
     *     
     */
    public ResourceValues getResourceValues() {
        return resourceValues;
    }

    /**
     * Sets the value of the resourceValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceValues }
     *     
     */
    public void setResourceValues(ResourceValues value) {
        this.resourceValues = value;
    }

    /**
     * Gets the value of the downlinkBandwidthValue property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDownlinkBandwidthValue() {
        return downlinkBandwidthValue;
    }

    /**
     * Sets the value of the downlinkBandwidthValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDownlinkBandwidthValue(Double value) {
        this.downlinkBandwidthValue = value;
    }

    /**
     * Gets the value of the uplinkBandwidthValue property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getUplinkBandwidthValue() {
        return uplinkBandwidthValue;
    }

    /**
     * Sets the value of the uplinkBandwidthValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setUplinkBandwidthValue(Double value) {
        this.uplinkBandwidthValue = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

}
