//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.29 at 10:28:31 AM CET 
//


package main.java.hspl_class;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the main.java.hspl_class package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: main.java.hspl_class
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Mapping }
     * 
     */
    public Mapping createMapping() {
        return new Mapping();
    }

    /**
     * Create an instance of {@link HSPLList }
     * 
     */
    public HSPLList createHSPLList() {
        return new HSPLList();
    }

    /**
     * Create an instance of {@link PSAList }
     * 
     */
    public PSAList createPSAList() {
        return new PSAList();
    }

    /**
     * Create an instance of {@link SolutionList }
     * 
     */
    public SolutionList createSolutionList() {
        return new SolutionList();
    }

    /**
     * Create an instance of {@link ServiceGraph }
     * 
     */
    public ServiceGraph createServiceGraph() {
        return new ServiceGraph();
    }

    /**
     * Create an instance of {@link MSPLList }
     * 
     */
    public MSPLList createMSPLList() {
        return new MSPLList();
    }

    /**
     * Create an instance of {@link RemediationList }
     * 
     */
    public RemediationList createRemediationList() {
        return new RemediationList();
    }

    /**
     * Create an instance of {@link Candidates }
     * 
     */
    public Candidates createCandidates() {
        return new Candidates();
    }

    /**
     * Create an instance of {@link CapabilityList }
     * 
     */
    public CapabilityList createCapabilityList() {
        return new CapabilityList();
    }

    /**
     * Create an instance of {@link Purpose }
     * 
     */
    public Purpose createPurpose() {
        return new Purpose();
    }

    /**
     * Create an instance of {@link ResourceValues }
     * 
     */
    public ResourceValues createResourceValues() {
        return new ResourceValues();
    }

    /**
     * Create an instance of {@link MSPL }
     * 
     */
    public MSPL createMSPL() {
        return new MSPL();
    }

    /**
     * Create an instance of {@link TimeInterval }
     * 
     */
    public TimeInterval createTimeInterval() {
        return new TimeInterval();
    }

    /**
     * Create an instance of {@link TrafficTarget }
     * 
     */
    public TrafficTarget createTrafficTarget() {
        return new TrafficTarget();
    }

    /**
     * Create an instance of {@link Edge }
     * 
     */
    public Edge createEdge() {
        return new Edge();
    }

    /**
     * Create an instance of {@link Solution }
     * 
     */
    public Solution createSolution() {
        return new Solution();
    }

    /**
     * Create an instance of {@link SuitableImplementationList }
     * 
     */
    public SuitableImplementationList createSuitableImplementationList() {
        return new SuitableImplementationList();
    }

    /**
     * Create an instance of {@link PSA }
     * 
     */
    public PSA createPSA() {
        return new PSA();
    }

    /**
     * Create an instance of {@link PSACharacteristic }
     * 
     */
    public PSACharacteristic createPSACharacteristic() {
        return new PSACharacteristic();
    }

    /**
     * Create an instance of {@link SuitablePSA }
     * 
     */
    public SuitablePSA createSuitablePSA() {
        return new SuitablePSA();
    }

    /**
     * Create an instance of {@link Service }
     * 
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link Remediationt }
     * 
     */
    public Remediationt createRemediationt() {
        return new Remediationt();
    }

    /**
     * Create an instance of {@link TypeContent }
     * 
     */
    public TypeContent createTypeContent() {
        return new TypeContent();
    }

    /**
     * Create an instance of {@link SpecificURL }
     * 
     */
    public SpecificURL createSpecificURL() {
        return new SpecificURL();
    }

    /**
     * Create an instance of {@link PSAInfo }
     * 
     */
    public PSAInfo createPSAInfo() {
        return new PSAInfo();
    }

    /**
     * Create an instance of {@link Hspl }
     * 
     */
    public Hspl createHspl() {
        return new Hspl();
    }

    /**
     * Create an instance of {@link NetworkFields }
     * 
     */
    public NetworkFields createNetworkFields() {
        return new NetworkFields();
    }

    /**
     * Create an instance of {@link Fields }
     * 
     */
    public Fields createFields() {
        return new Fields();
    }

    /**
     * Create an instance of {@link TimeHour }
     * 
     */
    public TimeHour createTimeHour() {
        return new TimeHour();
    }

    /**
     * Create an instance of {@link TimePeriod }
     * 
     */
    public TimePeriod createTimePeriod() {
        return new TimePeriod();
    }

}
