//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.29 at 10:28:31 AM CET 
//


package main.java.hspl_class;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Remediationt complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Remediationt">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="hspl" type="{http://www.example.org/Refinement_Schema}hspl" minOccurs="0"/>
 *         &lt;element name="mspl" type="{http://www.example.org/Refinement_Schema}MSPL" minOccurs="0"/>
 *         &lt;element name="suitablePSA" type="{http://www.example.org/Refinement_Schema}suitablePSA"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Remediationt", propOrder = {
    "hspl",
    "mspl",
    "suitablePSA"
})
public class Remediationt {

    protected Hspl hspl;
    protected MSPL mspl;
    @XmlElement(required = true)
    protected SuitablePSA suitablePSA;

    /**
     * Gets the value of the hspl property.
     * 
     * @return
     *     possible object is
     *     {@link Hspl }
     *     
     */
    public Hspl getHspl() {
        return hspl;
    }

    /**
     * Sets the value of the hspl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Hspl }
     *     
     */
    public void setHspl(Hspl value) {
        this.hspl = value;
    }

    /**
     * Gets the value of the mspl property.
     * 
     * @return
     *     possible object is
     *     {@link MSPL }
     *     
     */
    public MSPL getMspl() {
        return mspl;
    }

    /**
     * Sets the value of the mspl property.
     * 
     * @param value
     *     allowed object is
     *     {@link MSPL }
     *     
     */
    public void setMspl(MSPL value) {
        this.mspl = value;
    }

    /**
     * Gets the value of the suitablePSA property.
     * 
     * @return
     *     possible object is
     *     {@link SuitablePSA }
     *     
     */
    public SuitablePSA getSuitablePSA() {
        return suitablePSA;
    }

    /**
     * Sets the value of the suitablePSA property.
     * 
     * @param value
     *     allowed object is
     *     {@link SuitablePSA }
     *     
     */
    public void setSuitablePSA(SuitablePSA value) {
        this.suitablePSA = value;
    }

}
