//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.29 at 10:28:31 AM CET 
//


package main.java.hspl_class;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for Service complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Service">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PSA" type="{http://www.example.org/Refinement_Schema}PSA" minOccurs="0"/>
 *         &lt;element name="capability" type="{http://www.example.org/Refinement_Schema}capability" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="serviceID" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="MSPL_ID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Service", propOrder = {
    "psa",
    "capability"
})
public class Service {

    @XmlElement(name = "PSA")
    protected PSA psa;
    protected Capability capability;
    @XmlAttribute(name = "serviceID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String serviceID;
    @XmlAttribute(name = "MSPL_ID")
    protected String msplid;

    /**
     * Gets the value of the psa property.
     * 
     * @return
     *     possible object is
     *     {@link PSA }
     *     
     */
    public PSA getPSA() {
        return psa;
    }

    /**
     * Sets the value of the psa property.
     * 
     * @param value
     *     allowed object is
     *     {@link PSA }
     *     
     */
    public void setPSA(PSA value) {
        this.psa = value;
    }

    /**
     * Gets the value of the capability property.
     * 
     * @return
     *     possible object is
     *     {@link Capability }
     *     
     */
    public Capability getCapability() {
        return capability;
    }

    /**
     * Sets the value of the capability property.
     * 
     * @param value
     *     allowed object is
     *     {@link Capability }
     *     
     */
    public void setCapability(Capability value) {
        this.capability = value;
    }

    /**
     * Gets the value of the serviceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceID() {
        return serviceID;
    }

    /**
     * Sets the value of the serviceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceID(String value) {
        this.serviceID = value;
    }

    /**
     * Gets the value of the msplid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMSPLID() {
        return msplid;
    }

    /**
     * Sets the value of the msplid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMSPLID(String value) {
        this.msplid = value;
    }

}
