//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.07.14 at 02:12:36 PM CEST
//


package main.java.configuration_class;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="refinementType" use="required" type="{http://www.example.org/Configurations_Schema}refinementType" />
 *       &lt;attribute name="optimizationType" type="{http://www.example.org/Configurations_Schema}optimizationType" />
 *       &lt;attribute name="hspl_file" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="psa_file" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sg_input_file" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sg_ouput_file" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="mspl_dir_output" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="subject_file" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="content_file" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="target_file" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="maxEvaluationsNo" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="mspl_dir_input" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="user_psa_file" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="market_psa_file" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="remediation_file" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "configurations")
public class Configurations {

    @XmlAttribute(name = "refinementType", required = true)
    protected RefinementType refinementType;
    @XmlAttribute(name = "optimizationType")
    protected OptimizationType optimizationType;
    @XmlAttribute(name = "hspl_file", required = true)
    protected String hsplFile;
    @XmlAttribute(name = "psa_file")
    protected String psaFile;
    @XmlAttribute(name = "sg_input_file")
    protected String sgInputFile;
    @XmlAttribute(name = "sg_ouput_file")
    protected String sgOuputFile;
    @XmlAttribute(name = "mspl_dir_output")
    protected String msplDirOutput;
    @XmlAttribute(name = "subject_file")
    protected String subjectFile;
    @XmlAttribute(name = "content_file")
    protected String contentFile;
    @XmlAttribute(name = "target_file")
    protected String targetFile;
    @XmlAttribute(name = "description")
    protected String description;
    @XmlAttribute(name = "maxEvaluationsNo")
    protected Integer maxEvaluationsNo;
    @XmlAttribute(name = "mspl_dir_input")
    protected String msplDirInput;
    @XmlAttribute(name = "user_psa_file")
    protected String userPsaFile;
    @XmlAttribute(name = "market_psa_file")
    protected String marketPsaFile;
    @XmlAttribute(name = "remediation_file")
    protected String remediationFile;

    /**
     * Gets the value of the refinementType property.
     *
     * @return
     *     possible object is
     *     {@link RefinementType }
     *
     */
    public RefinementType getRefinementType() {
        return refinementType;
    }

    /**
     * Sets the value of the refinementType property.
     *
     * @param value
     *     allowed object is
     *     {@link RefinementType }
     *
     */
    public void setRefinementType(RefinementType value) {
        this.refinementType = value;
    }

    /**
     * Gets the value of the optimizationType property.
     *
     * @return
     *     possible object is
     *     {@link OptimizationType }
     *
     */
    public OptimizationType getOptimizationType() {
        return optimizationType;
    }

    /**
     * Sets the value of the optimizationType property.
     *
     * @param value
     *     allowed object is
     *     {@link OptimizationType }
     *
     */
    public void setOptimizationType(OptimizationType value) {
        this.optimizationType = value;
    }

    /**
     * Gets the value of the hsplFile property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getHsplFile() {
        return hsplFile;
    }

    /**
     * Sets the value of the hsplFile property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHsplFile(String value) {
        this.hsplFile = value;
    }

    /**
     * Gets the value of the psaFile property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPsaFile() {
        return psaFile;
    }

    /**
     * Sets the value of the psaFile property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPsaFile(String value) {
        this.psaFile = value;
    }

    /**
     * Gets the value of the sgInputFile property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSgInputFile() {
        return sgInputFile;
    }

    /**
     * Sets the value of the sgInputFile property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSgInputFile(String value) {
        this.sgInputFile = value;
    }

    /**
     * Gets the value of the sgOuputFile property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSgOuputFile() {
        return sgOuputFile;
    }

    /**
     * Sets the value of the sgOuputFile property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSgOuputFile(String value) {
        this.sgOuputFile = value;
    }

    /**
     * Gets the value of the msplDirOutput property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMsplDirOutput() {
        return msplDirOutput;
    }

    /**
     * Sets the value of the msplDirOutput property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMsplDirOutput(String value) {
        this.msplDirOutput = value;
    }

    /**
     * Gets the value of the subjectFile property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSubjectFile() {
        return subjectFile;
    }

    /**
     * Sets the value of the subjectFile property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSubjectFile(String value) {
        this.subjectFile = value;
    }

    /**
     * Gets the value of the contentFile property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getContentFile() {
        return contentFile;
    }

    /**
     * Sets the value of the contentFile property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setContentFile(String value) {
        this.contentFile = value;
    }

    /**
     * Gets the value of the targetFile property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTargetFile() {
        return targetFile;
    }

    /**
     * Sets the value of the targetFile property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTargetFile(String value) {
        this.targetFile = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the maxEvaluationsNo property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getMaxEvaluationsNo() {
        return maxEvaluationsNo;
    }

    /**
     * Sets the value of the maxEvaluationsNo property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setMaxEvaluationsNo(Integer value) {
        this.maxEvaluationsNo = value;
    }

    /**
     * Gets the value of the msplDirInput property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMsplDirInput() {
        return msplDirInput;
    }

    /**
     * Sets the value of the msplDirInput property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMsplDirInput(String value) {
        this.msplDirInput = value;
    }

    /**
     * Gets the value of the userPsaFile property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getUserPsaFile() {
        return userPsaFile;
    }

    /**
     * Sets the value of the userPsaFile property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setUserPsaFile(String value) {
        this.userPsaFile = value;
    }

    /**
     * Gets the value of the marketPsaFile property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMarketPsaFile() {
        return marketPsaFile;
    }

    /**
     * Sets the value of the marketPsaFile property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMarketPsaFile(String value) {
        this.marketPsaFile = value;
    }

    /**
     * Gets the value of the remediationFile property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRemediationFile() {
        return remediationFile;
    }

    /**
     * Sets the value of the remediationFile property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRemediationFile(String value) {
        this.remediationFile = value;
    }

}
