//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.07.14 at 02:12:36 PM CEST
//


package main.java.configuration_class;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for refinementType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="refinementType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Policy_HSPL"/>
 *     &lt;enumeration value="Policy_MSPL"/>
 *     &lt;enumeration value="Application_HSPL"/>
 *     &lt;enumeration value="Application_MSPL"/>
 *     &lt;enumeration value="Application_MSPL_SG"/>
 *     &lt;enumeration value="Application_HSPL_SG"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "refinementType")
@XmlEnum
public enum RefinementType {

    @XmlEnumValue("Policy_HSPL")
    POLICY_HSPL("Policy_HSPL"),
    @XmlEnumValue("Policy_MSPL")
    POLICY_MSPL("Policy_MSPL"),
    @XmlEnumValue("Application_HSPL")
    APPLICATION_HSPL("Application_HSPL"),
    @XmlEnumValue("Application_MSPL")
    APPLICATION_MSPL("Application_MSPL"),
    @XmlEnumValue("Application_MSPL_SG")
    APPLICATION_MSPL_SG("Application_MSPL_SG"),
    @XmlEnumValue("Application_HSPL_SG")
    APPLICATION_HSPL_SG("Application_HSPL_SG");
    private final String value;

    RefinementType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RefinementType fromValue(String v) {
        for (RefinementType c: RefinementType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
