//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.19 at 01:07:32 PM CEST 
//


package main.java.associationList_class;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the main.java.associationList_class package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: main.java.associationList_class
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AssociationList }
     * 
     */
    public AssociationList createAssociationList() {
        return new AssociationList();
    }

    /**
     * Create an instance of {@link Association }
     * 
     */
    public Association createAssociation() {
        return new Association();
    }

    /**
     * Create an instance of {@link MimeType }
     * 
     */
    public MimeType createMimeType() {
        return new MimeType();
    }

    /**
     * Create an instance of {@link RE }
     * 
     */
    public RE createRE() {
        return new RE();
    }

    /**
     * Create an instance of {@link VPN }
     * 
     */
    public VPN createVPN() {
        return new VPN();
    }

    /**
     * Create an instance of {@link IP }
     * 
     */
    public IP createIP() {
        return new IP();
    }

    /**
     * Create an instance of {@link Cert }
     * 
     */
    public Cert createCert() {
        return new Cert();
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link Autentication }
     * 
     */
    public Autentication createAutentication() {
        return new Autentication();
    }

    /**
     * Create an instance of {@link URI }
     * 
     */
    public URI createURI() {
        return new URI();
    }

}
