//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.19 at 01:07:32 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/AssociationList", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package main.java.associationList_class;
