//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.19 at 01:07:32 PM CEST 
//


package main.java.associationList_class;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VPN complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VPN">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="autentication" type="{http://www.example.org/AssociationList}autentication" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="localEndpoint" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="remoteEndpint" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="localSubNet" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="remoteSubNet" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VPN", propOrder = {
    "autentication"
})
public class VPN {

    protected Autentication autentication;
    @XmlAttribute(name = "localEndpoint")
    protected String localEndpoint;
    @XmlAttribute(name = "remoteEndpint")
    protected String remoteEndpint;
    @XmlAttribute(name = "localSubNet")
    protected String localSubNet;
    @XmlAttribute(name = "remoteSubNet")
    protected String remoteSubNet;

    /**
     * Gets the value of the autentication property.
     * 
     * @return
     *     possible object is
     *     {@link Autentication }
     *     
     */
    public Autentication getAutentication() {
        return autentication;
    }

    /**
     * Sets the value of the autentication property.
     * 
     * @param value
     *     allowed object is
     *     {@link Autentication }
     *     
     */
    public void setAutentication(Autentication value) {
        this.autentication = value;
    }

    /**
     * Gets the value of the localEndpoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalEndpoint() {
        return localEndpoint;
    }

    /**
     * Sets the value of the localEndpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalEndpoint(String value) {
        this.localEndpoint = value;
    }

    /**
     * Gets the value of the remoteEndpint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemoteEndpint() {
        return remoteEndpint;
    }

    /**
     * Sets the value of the remoteEndpint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemoteEndpint(String value) {
        this.remoteEndpint = value;
    }

    /**
     * Gets the value of the localSubNet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalSubNet() {
        return localSubNet;
    }

    /**
     * Sets the value of the localSubNet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalSubNet(String value) {
        this.localSubNet = value;
    }

    /**
     * Gets the value of the remoteSubNet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemoteSubNet() {
        return remoteSubNet;
    }

    /**
     * Sets the value of the remoteSubNet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemoteSubNet(String value) {
        this.remoteSubNet = value;
    }

}
