//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.29 at 12:19:02 PM CET 
//


package eu.fp7.secured.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for hspl complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="hspl">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="action" type="{http://www.example.org/Refinement_Schema}action"/>
 *         &lt;element name="objectH" type="{http://www.example.org/Refinement_Schema}objectH"/>
 *         &lt;element name="fields" type="{http://www.example.org/Refinement_Schema}fields" minOccurs="0"/>
 *         &lt;element name="capabilities" type="{http://www.example.org/Refinement_Schema}capability_list" minOccurs="0"/>
 *         &lt;element name="candidates" type="{http://www.example.org/Refinement_Schema}Candidates" minOccurs="0"/>
 *         &lt;element name="suitableImplementation" type="{http://www.example.org/Refinement_Schema}suitableImplementation_list" minOccurs="0"/>
 *         &lt;element name="non-enforzable-Capability" type="{http://www.example.org/Refinement_Schema}capability_list" minOccurs="0"/>
 *         &lt;element name="implementation" type="{http://www.example.org/Refinement_Schema}PSA_list" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="subject" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="enforzability" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hspl", propOrder = {
    "action",
    "objectH",
    "fields",
    "capabilities",
    "candidates",
    "suitableImplementation",
    "nonEnforzableCapability",
    "implementation"
})
public class Hspl {

    @XmlElement(required = true)
    protected Action action;
    @XmlElement(required = true)
    protected ObjectH objectH;
    protected Fields fields;
    protected CapabilityList capabilities;
    protected Candidates candidates;
    protected SuitableImplementationList suitableImplementation;
    @XmlElement(name = "non-enforzable-Capability")
    protected CapabilityList nonEnforzableCapability;
    protected PSAList implementation;
    @XmlAttribute
    protected String subject;
    @XmlAttribute
    protected Boolean enforzability;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link Action }
     *     
     */
    public Action getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link Action }
     *     
     */
    public void setAction(Action value) {
        this.action = value;
    }

    /**
     * Gets the value of the objectH property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectH }
     *     
     */
    public ObjectH getObjectH() {
        return objectH;
    }

    /**
     * Sets the value of the objectH property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectH }
     *     
     */
    public void setObjectH(ObjectH value) {
        this.objectH = value;
    }

    /**
     * Gets the value of the fields property.
     * 
     * @return
     *     possible object is
     *     {@link Fields }
     *     
     */
    public Fields getFields() {
        return fields;
    }

    /**
     * Sets the value of the fields property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fields }
     *     
     */
    public void setFields(Fields value) {
        this.fields = value;
    }

    /**
     * Gets the value of the capabilities property.
     * 
     * @return
     *     possible object is
     *     {@link CapabilityList }
     *     
     */
    public CapabilityList getCapabilities() {
        return capabilities;
    }

    /**
     * Sets the value of the capabilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link CapabilityList }
     *     
     */
    public void setCapabilities(CapabilityList value) {
        this.capabilities = value;
    }

    /**
     * Gets the value of the candidates property.
     * 
     * @return
     *     possible object is
     *     {@link Candidates }
     *     
     */
    public Candidates getCandidates() {
        return candidates;
    }

    /**
     * Sets the value of the candidates property.
     * 
     * @param value
     *     allowed object is
     *     {@link Candidates }
     *     
     */
    public void setCandidates(Candidates value) {
        this.candidates = value;
    }

    /**
     * Gets the value of the suitableImplementation property.
     * 
     * @return
     *     possible object is
     *     {@link SuitableImplementationList }
     *     
     */
    public SuitableImplementationList getSuitableImplementation() {
        return suitableImplementation;
    }

    /**
     * Sets the value of the suitableImplementation property.
     * 
     * @param value
     *     allowed object is
     *     {@link SuitableImplementationList }
     *     
     */
    public void setSuitableImplementation(SuitableImplementationList value) {
        this.suitableImplementation = value;
    }

    /**
     * Gets the value of the nonEnforzableCapability property.
     * 
     * @return
     *     possible object is
     *     {@link CapabilityList }
     *     
     */
    public CapabilityList getNonEnforzableCapability() {
        return nonEnforzableCapability;
    }

    /**
     * Sets the value of the nonEnforzableCapability property.
     * 
     * @param value
     *     allowed object is
     *     {@link CapabilityList }
     *     
     */
    public void setNonEnforzableCapability(CapabilityList value) {
        this.nonEnforzableCapability = value;
    }

    /**
     * Gets the value of the implementation property.
     * 
     * @return
     *     possible object is
     *     {@link PSAList }
     *     
     */
    public PSAList getImplementation() {
        return implementation;
    }

    /**
     * Sets the value of the implementation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PSAList }
     *     
     */
    public void setImplementation(PSAList value) {
        this.implementation = value;
    }

    /**
     * Gets the value of the subject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubject(String value) {
        this.subject = value;
    }

    /**
     * Gets the value of the enforzability property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isEnforzability() {
        if (enforzability == null) {
            return true;
        } else {
            return enforzability;
        }
    }

    /**
     * Sets the value of the enforzability property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnforzability(Boolean value) {
        this.enforzability = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
