//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.29 at 12:19:02 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/Refinement_Schema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package eu.fp7.secured.xml;
