//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.29 at 12:19:02 PM CET 
//


package eu.fp7.secured.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PSA complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PSA">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PSA_info" type="{http://www.example.org/Refinement_Schema}PSA_info" minOccurs="0"/>
 *         &lt;element name="PSA_characteristic" type="{http://www.example.org/Refinement_Schema}PSA_characteristic"/>
 *         &lt;element name="capability" type="{http://www.example.org/Refinement_Schema}capability_list"/>
 *         &lt;element name="MSPL_list" type="{http://www.example.org/Refinement_Schema}MSPL_list" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PSA", propOrder = {
    "psaInfo",
    "psaCharacteristic",
    "capability",
    "msplList"
})
public class PSA {

    @XmlElement(name = "PSA_info")
    protected PSAInfo psaInfo;
    @XmlElement(name = "PSA_characteristic", required = true)
    protected PSACharacteristic psaCharacteristic;
    @XmlElement(required = true)
    protected CapabilityList capability;
    @XmlElement(name = "MSPL_list")
    protected MSPLList msplList;
    @XmlAttribute
    protected String name;

    /**
     * Gets the value of the psaInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PSAInfo }
     *     
     */
    public PSAInfo getPSAInfo() {
        return psaInfo;
    }

    /**
     * Sets the value of the psaInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PSAInfo }
     *     
     */
    public void setPSAInfo(PSAInfo value) {
        this.psaInfo = value;
    }

    /**
     * Gets the value of the psaCharacteristic property.
     * 
     * @return
     *     possible object is
     *     {@link PSACharacteristic }
     *     
     */
    public PSACharacteristic getPSACharacteristic() {
        return psaCharacteristic;
    }

    /**
     * Sets the value of the psaCharacteristic property.
     * 
     * @param value
     *     allowed object is
     *     {@link PSACharacteristic }
     *     
     */
    public void setPSACharacteristic(PSACharacteristic value) {
        this.psaCharacteristic = value;
    }

    /**
     * Gets the value of the capability property.
     * 
     * @return
     *     possible object is
     *     {@link CapabilityList }
     *     
     */
    public CapabilityList getCapability() {
        return capability;
    }

    /**
     * Sets the value of the capability property.
     * 
     * @param value
     *     allowed object is
     *     {@link CapabilityList }
     *     
     */
    public void setCapability(CapabilityList value) {
        this.capability = value;
    }

    /**
     * Gets the value of the msplList property.
     * 
     * @return
     *     possible object is
     *     {@link MSPLList }
     *     
     */
    public MSPLList getMSPLList() {
        return msplList;
    }

    /**
     * Sets the value of the msplList property.
     * 
     * @param value
     *     allowed object is
     *     {@link MSPLList }
     *     
     */
    public void setMSPLList(MSPLList value) {
        this.msplList = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
