//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.29 at 12:19:02 PM CET 
//


package eu.fp7.secured.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for time_interval complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="time_interval">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="week_day" type="{http://www.example.org/Refinement_Schema}week_day" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="time_hours" type="{http://www.example.org/Refinement_Schema}time_hour" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "time_interval", propOrder = {
    "weekDay",
    "timeHours"
})
public class TimeInterval {

    @XmlElement(name = "week_day")
    protected List<WeekDay> weekDay;
    @XmlElement(name = "time_hours")
    protected List<TimeHour> timeHours;

    /**
     * Gets the value of the weekDay property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the weekDay property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWeekDay().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WeekDay }
     * 
     * 
     */
    public List<WeekDay> getWeekDay() {
        if (weekDay == null) {
            weekDay = new ArrayList<WeekDay>();
        }
        return this.weekDay;
    }

    /**
     * Gets the value of the timeHours property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the timeHours property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTimeHours().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TimeHour }
     * 
     * 
     */
    public List<TimeHour> getTimeHours() {
        if (timeHours == null) {
            timeHours = new ArrayList<TimeHour>();
        }
        return this.timeHours;
    }

}
